EventsPro/Controllers/ImagesController.cs
using Event.Application.Common.Helper;
using Event.Application.Features.Images.Commands.CreateImages;
using Event.Application.Features.Images.Commands.DeleteImages;
using Event.Application.Features.Images.Commands.UpdateImages;
using Event.Application.Features.Images.Queries.GetImagesDetails;
using Event.Application.Features.Images.Queries.GetImagesList;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Event.Web.Controllers
{
    public class ImagesController : Controller
    {
        private readonly IMediator _mediator;

        public ImagesController(IMediator mediator)
        {
            _mediator = mediator;
        }


        [HttpGet]
        public async Task<ActionResult<List<GetImagesListViewModel>>> GetListImages(Guid Id)
        {
            ViewBag.AlbumId = Id;
            return View(await _mediator.Send(new GetImagesListQuery() { AlbumId = Id }));
        }


        [HttpGet]
        public async Task<ActionResult<GetImagesDetailsViewModel>> GetImageById(Guid Id)
        {
            return View(await _mediator.Send(new GetImagesDetailsQuery() { ImageId = Id }));
        }


        [HttpGet]
        public IActionResult CreateImage(Guid AlbumId)
        {
            ViewBag.AlbumId = AlbumId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateImage([FromForm] CreateImagesCommand createAlbumCommand)
        {
            Guid id = await _mediator.Send(createAlbumCommand);

            return RedirectToAction(nameof(GetListImages), new { id = createAlbumCommand.AlbumId });
        }


        [HttpGet]
        public async Task<ActionResult<GetImagesDetailsViewModel>> UpdateImage(Guid Id)
        {
            return View(await _mediator.Send(new GetImagesDetailsQuery() { ImageId = Id }));
        }

        [HttpPost]
        public async Task<ActionResult> UpdateImage([FromForm] UpdateImagesCommand updateImageCommand)
        {
            await _mediator.Send(updateImageCommand);

            return RedirectToAction(nameof(GetListImages), new { Id = updateImageCommand.AlbumId });
        }

        [HttpPost]
        public async Task<ActionResult> DeleteImage(Guid id)
        {
            await _mediator.Send(new DeleteImagesCommand() { ImageId = id });

            return Ok(new { key = 1 });
        }
    }
}

EventsPro/Views/Images/CreateImage.cshtml
@model Event.Application.Features.Images.Commands.CreateImages.CreateImagesCommand
@{
    ViewData["Title"] = "Create";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">اضافة صوره</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="CreateImage" asp-controller="Images" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div>
                    <input hidden asp-for="AlbumId" value="@ViewBag.AlbumId" class="form-control" />
                </div>   
                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label">الصوره</label>
                    <input type="file" asp-for="ImageFile" class="form-control" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
               
                <div class="form-group">
                    <input type="submit" value="اضافة" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListImages" asp-route-id="@ViewBag.AlbumId" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

EventsPro/Views/Images/GetListImages.cshtml
@model IEnumerable<Event.Application.Features.Images.Queries.GetImagesList.GetImagesListViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card-box">

    <h2 class="header-title m-t-0 m-b-30">الصور</h2>

    <div>
        <p>
            @Html.ActionLink("اضافة صوره", "CreateImage", "Images", new {AlbumId = ViewBag.AlbumId }, new { @class = "btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" })
        </p>
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th> الصوره </th>
                    <th>تعديل</th>
                    <th>حذف</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <img src="@Event.Application.Common.PathUrl.DashBordUrl.baseUrlHost@item.Image" width="50" />
                        </td>

                        <td>
                            <a href="/Images/UpdateImage/@item.Id" class="btn btn-info btn-rounded" role="button" aria-pressed="true">تعديل</a>
                        </td>
                        <td>
                            <input type="button" value="&#xf014;" class="icon-font btn btn-danger btn-rounded" onclick="Delete('@item.Id')" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!-- -------------------------------------------------------------------------------------------------- -->
    </div><!-- end row -->
</div>
@*
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="jquery-3.6.0.min.js"></script>*@

@section scripts
{
<script>

    function Delete(id) {
         Swal.fire({
             title: 'هل انت متاكد من حذف هذا العنصر  ؟',
             type: 'warning',
             showCancelButton: true,
             confirmButtonColor: '#d33',
             cancelButtonColor: '#3085d6',
             cancelButtonText: 'اغلاق',
             confirmButtonText: 'حذف',
         }).then((result) => {
             if (result.value) {
                 $.ajax({
                     url: "/Images/DeleteImage",
                     type: "POST",
                     dataType: "json",
                     data: {
                         id: id
                     }, success: function (result) {
                         if (result.data == true) {
                             toastr.success("تم الحذف بنجاح");
                             setTimeout(function () {
                             }, 3000);
                         }
                         window.location.reload();
                     },
                     failure: function (info) {

                     }
                 })
             }
         })
     }

</script>
}

EventsPro/Views/Images/UpdateImage.cshtml
@model  Event.Application.Features.Images.Queries.GetImagesDetails.GetImagesDetailsViewModel


@{
    ViewData["Title"] = "Edit";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">تعديل</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="UpdateImage" asp-controller="Images" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="AlbumId" />
                <input type="hidden" asp-for="Image" />

                 <div class="form-group">
                    <label asp-for="Image" class="control-label">صورة القديمة</label>
                    <div class="col-md-10">
                        <img src="@Event.Application.Common.PathUrl.DashBordUrl.baseUrlHost@Model.Image" style="width:100px; height:100px; " />
                    </div>
                </div>
             
                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label">صورة جديدة</label>
                    <input asp-for="ImageFile" class="form-control" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <input type="submit" value="حفظ" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListImages"  asp-route-id="@Model.AlbumId" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}